# Rename this file as `secrets.yml` and add your betterdoctor user key

development:
  secret_key_base: development_secret_base
  betterdoctor_api_key: replace_with_key

test:
  secret_key_base: test_secret_base
  betterdoctor_api_key: replace_with_key

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  betterdoctor_api_key: <%= ENV["BETTERDOCTOR_API_KEY"] %>
